# define WINDOW_WIDTH						592
# define WINDOW_HEIGHT						370

# define MODE_V_MRGN						12
# define MODE_H_MRGN						12
# define MODE_HEIGHT						30

# define	LIST_WIDTH						86
# define	LIST_H_MRGN						6
# define	LIST_T_HEIGHT					100
# define	LIST_HEIGHT						24

# define		MODE_BUTTON_WIDTH			80
# define		MODE_BUTTON_HEIGHT			26
//# define		MODE_BUTTON_T_HEIGHT		LIST_T_HEIGHT
# define		MODE_BUTTON_H_MRGN			MODE_H_MRGN
# define		MODE_BUTTON_V_MRGN			MODE_V_MRGN

# define		MODE_G_BUTTON_V_MRGN		MODE_V_MRGN+(MODE_BUTTON_HEIGHT-LIST_HEIGHT)/2

# define		GROUP_LIST_WIDTH			LIST_WIDTH
# define		GROUP_LIST_T_HEIGHT			LIST_T_HEIGHT
# define		GROUP_LIST_H_MRGN			MODE_BUTTON_H_MRGN+MODE_BUTTON_WIDTH+LIST_H_MRGN
# define		GROUP_LIST_V_MRGN			MODE_G_BUTTON_V_MRGN

# define		TYPE_LIST_WIDTH				LIST_WIDTH
# define		TYPE_LIST_T_HEIGHT			LIST_T_HEIGHT
# define		TYPE_LIST_H_MRGN			GROUP_LIST_H_MRGN+GROUP_LIST_WIDTH+LIST_H_MRGN
# define		TYPE_LIST_V_MRGN			MODE_G_BUTTON_V_MRGN

# define		OPTIONS_BUTTON_WIDTH		70
# define		OPTIONS_BUTTON_HEIGHT		24
# define		OPTIONS_BUTTON_H_MRGN		TYPE_LIST_H_MRGN+TYPE_LIST_WIDTH+LIST_H_MRGN
# define		OPTIONS_BUTTON_V_MRGN		MODE_G_BUTTON_V_MRGN

# define		CHECKSUM_BUTTON_WIDTH		76
# define		CHECKSUM_BUTTON_HEIGHT		24
# define		CHECKSUM_BUTTON_H_MRGN		OPTIONS_BUTTON_H_MRGN+OPTIONS_BUTTON_WIDTH+LIST_H_MRGN
# define		CHECKSUM_BUTTON_V_MRGN		MODE_G_BUTTON_V_MRGN

# define		BROWSE_BUTTON_WIDTH			66
# define		BROWSE_BUTTON_HEIGHT		24
# define		BROWSE_BUTTON_H_MRGN		CHECKSUM_BUTTON_H_MRGN+CHECKSUM_BUTTON_WIDTH+LIST_H_MRGN
# define		BROWSE_BUTTON_V_MRGN		MODE_G_BUTTON_V_MRGN

# define		ABOUT_BUTTON_WIDTH			24
# define		ABOUT_BUTTON_HEIGHT			24
# define		ABOUT_BUTTON_H_MRGN			WINDOW_WIDTH-MODE_H_MRGN-ABOUT_BUTTON_WIDTH
# define		ABOUT_BUTTON_V_MRGN			MODE_G_BUTTON_V_MRGN

# define		SAVE_MODE_BUTTON_WIDTH		24
# define		SAVE_MODE_BUTTON_HEIGHT		24
# define		SAVE_MODE_BUTTON_H_MRGN		ABOUT_BUTTON_H_MRGN-LIST_H_MRGN-SAVE_MODE_BUTTON_WIDTH
# define		SAVE_MODE_BUTTON_V_MRGN		MODE_G_BUTTON_V_MRGN

# define BOX_H_MRGN							10
# define BOX_V_MRGN							8
# define BOX_WIDTH							474
# define BOX_HEIGHT							146

# define IN_OUT_GAP							16

# define CP_BUTTON_NUMBER					3
# define CP_BUTTON_WIDTH					60	
# define CP_BUTTON_HEIGHT					26
# define CP_BUTTON_H_MRGN					(IN_BOX_H_MRGN+IN_BOX_WIDTH)+((WINDOW_WIDTH-(IN_BOX_H_MRGN+IN_BOX_WIDTH))-CP_BUTTON_WIDTH)/2
# define CP_BUTTON_V_MRGN					(IN_BOX_HEIGHT-(CP_BUTTON_HEIGHT*CP_BUTTON_NUMBER+CP_BUTTON_V_GAP*(CP_BUTTON_NUMBER-1)))/2
# define CP_BUTTON_V_GAP					6

# define		IN_BOX_H_MRGN				BOX_H_MRGN
# define		IN_BOX_V_MRGN				MODE_V_MRGN+MODE_HEIGHT+BOX_V_MRGN
# define		IN_BOX_WIDTH				BOX_WIDTH
# define		IN_BOX_HEIGHT				BOX_HEIGHT

# define		IN_COPY_BUTTON_WIDTH		CP_BUTTON_WIDTH
# define		IN_COPY_BUTTON_HEIGHT		CP_BUTTON_HEIGHT
# define		IN_COPY_BUTTON_H_MRGN		CP_BUTTON_H_MRGN
# define		IN_COPY_BUTTON_V_MRGN		IN_BOX_V_MRGN+CP_BUTTON_V_MRGN

# define		IN_PASTE_BUTTON_WIDTH		CP_BUTTON_WIDTH
# define		IN_PASTE_BUTTON_HEIGHT		CP_BUTTON_HEIGHT
# define		IN_PASTE_BUTTON_H_MRGN		CP_BUTTON_H_MRGN
# define		IN_PASTE_BUTTON_V_MRGN		IN_COPY_BUTTON_V_MRGN+IN_COPY_BUTTON_HEIGHT+CP_BUTTON_V_GAP

# define		IN_CLEAR_BUTTON_WIDTH		CP_BUTTON_WIDTH
# define		IN_CLEAR_BUTTON_HEIGHT		CP_BUTTON_HEIGHT
# define		IN_CLEAR_BUTTON_H_MRGN		CP_BUTTON_H_MRGN
# define		IN_CLEAR_BUTTON_V_MRGN		IN_PASTE_BUTTON_V_MRGN+IN_PASTE_BUTTON_HEIGHT+CP_BUTTON_V_GAP

# define		CONVERT_BOX_WIDTH			484
# define		CONVERT_BOX_HEIGHT			100

# define			CONVERT_BUTTON_WIDTH	80
# define			CONVERT_BUTTON_HEIGHT	34
# define			CONVERT_BUTTON_H_MRGN	(IN_BOX_H_MRGN+IN_BOX_WIDTH)+((WINDOW_WIDTH-(IN_BOX_H_MRGN+IN_BOX_WIDTH))-CONVERT_BUTTON_WIDTH)/2//BOX_H_MRGN+(BOX_WIDTH-CONVERT_BUTTON_WIDTH)/2
# define			CONVERT_BUTTON_V_MRGN	IN_BOX_V_MRGN+IN_BOX_HEIGHT+(IN_OUT_GAP-CONVERT_BUTTON_HEIGHT)/2

# ifdef TEST
# define		CYCLE_BUTTON_WIDTH			CP_BUTTON_WIDTH
# define		CYCLE_BUTTON_HEIGHT			CP_BUTTON_HEIGHT-2
# define		CYCLE_BUTTON_H_MRGN			CP_BUTTON_H_MRGN
# define		CYCLE_BUTTON_V_MRGN			OUT_BOX_V_MRGN+OUT_BOX_HEIGHT-(CYCLE_BUTTON_HEIGHT-4)
# endif

# define		OUT_BOX_H_MRGN				BOX_H_MRGN
# define		OUT_BOX_V_MRGN				IN_BOX_V_MRGN+IN_BOX_HEIGHT+IN_OUT_GAP
# define		OUT_BOX_WIDTH				BOX_WIDTH
# define		OUT_BOX_HEIGHT				BOX_HEIGHT

# define		OUT_COPY_BUTTON_WIDTH		CP_BUTTON_WIDTH
# define		OUT_COPY_BUTTON_HEIGHT		CP_BUTTON_HEIGHT
# define		OUT_COPY_BUTTON_H_MRGN		CP_BUTTON_H_MRGN
# define		OUT_COPY_BUTTON_V_MRGN		OUT_BOX_V_MRGN+CP_BUTTON_V_MRGN

# define		OUT_PASTE_BUTTON_WIDTH		CP_BUTTON_WIDTH
# define		OUT_PASTE_BUTTON_HEIGHT		CP_BUTTON_HEIGHT
# define		OUT_PASTE_BUTTON_H_MRGN		CP_BUTTON_H_MRGN
# define		OUT_PASTE_BUTTON_V_MRGN		OUT_COPY_BUTTON_V_MRGN+OUT_COPY_BUTTON_HEIGHT+CP_BUTTON_V_GAP

# define		OUT_CLEAR_BUTTON_WIDTH		CP_BUTTON_WIDTH
# define		OUT_CLEAR_BUTTON_HEIGHT		CP_BUTTON_HEIGHT
# define		OUT_CLEAR_BUTTON_H_MRGN		CP_BUTTON_H_MRGN
# define		OUT_CLEAR_BUTTON_V_MRGN		OUT_PASTE_BUTTON_V_MRGN+OUT_PASTE_BUTTON_HEIGHT+CP_BUTTON_V_GAP

# define		SUG_BOX_H_MRGN				OUT_BOX_H_MRGN
# define		SUG_BOX_V_MRGN				OUT_BOX_V_MRGN
# define		SUG_BOX_WIDTH				OUT_BOX_WIDTH
# define		SUG_BOX_HEIGHT				OUT_BOX_HEIGHT
